import React from 'react'
import Styles from './Publicidad.module.css'

export default function Publicidad() {
  return (
    <div className={Styles['parques__detalle-parque-publicidad']}>
      <p>hola publicidad Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ullam, nihil consequuntur! Ut, magni ratione voluptatem alias provident ullam fugiat minima unde tenetur dolores est numquam neque quasi sunt ipsam cum, quidem voluptates vero adipisci iste ab totam! Eum, officia amet! Dignissimos delectus et facere alias animi odio, voluptates dolorem, nisi omnis ullam voluptate. Eius doloremque, rem debitis eligendi reprehenderit qui nulla consequuntur eaque ullam facere velit amet possimus doloribus dolor sequi pariatur consectetur deserunt perferendis enim sit nihil officiis ad? Magni eaque a repellendus minus nulla dolore corporis saepe autem minima illo sequi itaque fugiat est aperiam quis consequuntur dolorum, ullam vitae, illum quaerat officia? Aspernatur minima, dolore consequatur, assumenda accusantium quae sit, dolorem asperiores temporibus ex fugit officia. Accusantium a ipsa aliquam quae, eius velit commodi beatae rem reiciendis minus corporis dolore quo in. Sunt molestiae inventore animi necessitatibus suscipit soluta reiciendis esse voluptatum eos accusamus consequuntur, aliquid in quia? Dolorem tempore est id perferendis qui vitae. Eveniet fuga nulla hic repudiandae, eum assumenda itaque voluptatibus incidunt ipsam praesentium necessitatibus a dignissimos soluta. Ducimus quos tenetur, praesentium impedit vel sequi corrupti odio magnam illum. Sed eius consequuntur possimus, totam facere animi. Excepturi eos vitae adipisci ut aliquid eaque eum reprehenderit ducimus est commodi. Eveniet, excepturi fugit? Fugit, blanditiis autem? Sunt nesciunt harum libero inventore ut aut quibusdam, provident, molestias expedita distinctio cupiditate nihil excepturi tempore accusantium dicta, ullam temporibus modi? Aspernatur natus, quo, nemo aut cumque error consequuntur veritatis totam quisquam, atque animi hic? Distinctio accusamus labore numquam rem, vel nobis neque vero earum consectetur unde saepe mollitia tempore laborum laudantium, error ad sunt et. Et adipisci earum fugit eaque neque voluptates, debitis placeat, sit ab doloribus magni. Tempora iure id earum accusamus fugiat, deleniti repudiandae. Odit, tempora. Itaque officiis non architecto. Sit, est. Facilis odit magnam soluta dolor eveniet veniam deserunt nemo magni. Ipsa dolor ratione rerum modi accusamus ex atque dolorem fugiat ullam quisquam vel veritatis doloribus, eaque maxime magni odit libero, amet veniam labore mollitia reiciendis consectetur quae! Sapiente ab perspiciatis mollitia placeat ducimus molestiae. Autem qui est, non ut quos illo explicabo beatae aspernatur velit veritatis nisi laborum minus quae maiores impedit. In nostrum itaque aperiam quasi doloremque veniam sequi sapiente, totam voluptates repudiandae quis ex sed rem minus beatae delectus quisquam, quod adipisci quas, exercitationem ipsa sit impedit? Quia error rerum itaque ratione provident recusandae corrupti labore nisi ut, quibusdam expedita nemo dicta totam.</p>
    </div>
  )
}
