const parques = [
  {
    id: 1,
    nombre: "Parque Central",
    direccion: "Av. Principal 123, Durán, Ecuador",
    canton: "Durán",
    pais: "Ecuador",
    continente: "Sudamérica",
    latitud: -2.158973,
    longitud: -79.835622,
    puntuacion: 4.5,
    descripcion: "Un parque amplio con áreas para calistenia y zonas recreativas.",
    imagen: "https://mobipark.com/wp-content/uploads/2023/02/trainingbox-joc-58-jaula-de-ejercicios-02g-1.jpg",
  },
  {
    id: 2,
    nombre: "Parque de la Amistad",
    direccion: "Calle Secundaria 456, Guayaquil, Ecuador",
    canton: "Guayaquil",
    pais: "Ecuador",
    continente: "Sudamérica",
    latitud: -2.190100,
    longitud: -79.882700,
    puntuacion: 5.0,
    descripcion: "Parque ideal para entrenamientos al aire libre, equipado con barras y pesas.",
    imagen: "https://www.krealiagestion.com/wp-content/uploads/2017/06/ventajas-de-tener-un-parque-de-calistenia-cerca-Krealia-1.jpg",
  },
  {
    id: 3,
    nombre: "Parque de los Sueños",
    direccion: "Calle Tercera 789, Quito, Ecuador",
    canton: "Quito",
    pais: "Ecuador",
    continente: "Sudamérica",
    latitud: -0.220164,
    longitud: -78.512327,
    puntuacion: 3.8,
    descripcion: "Parque pequeño pero acogedor con algunas barras y áreas verdes.",
    imagen: "https://equidesa.com/media/redactor/Calistenia%20Equidesa%20Gandia%201.JPG",
  },
  {
    id: 4,
    nombre: "Parque del Sol",
    direccion: "Av. Sol Naciente 987, Cuenca, Ecuador",
    canton: "Cuenca",
    pais: "Ecuador",
    continente: "Sudamérica",
    latitud: -2.899506,
    longitud: -79.010634,
    puntuacion: 4.2,
    descripcion: "Zona perfecta para disfrutar del sol mientras entrenas al aire libre.",
    imagen: "https://cdn.pixabay.com/photo/2016/11/29/05/35/playground-1866475_1280.jpg",
  },
  {
    id: 5,
    nombre: "Parque La Libertad",
    direccion: "Calle Libertad 123, Manta, Ecuador",
    canton: "Manta",
    pais: "Ecuador",
    continente: "Sudamérica",
    latitud: -0.947225,
    longitud: -80.708918,
    puntuacion: 4.7,
    descripcion: "Equipado con modernas instalaciones para entrenamientos funcionales.",
    imagen: "https://cdn.pixabay.com/photo/2017/08/10/02/47/gym-2611694_1280.jpg",
  },
];

export default parques